### ISSUE TITLE
Extend speaker model according to iosched3 model

### ISSUE THREAD

**Issue by printminion** [GoogleDeveloperGroups/devfest-site#1]
Please extend current speaker model according to iosched3 model (we need it for the app)
https://github.com/GoogleDeveloperGroups/devfest-site/blob/master/devfest-site/lib/model.py

{
bio: "Reto is the tech lead for the Android Developer Relations team. He is currently focussed on programs such as Android Developers Live and Android Training and is also the author of “Professional Android 4 Application Development”.",
first_name: "Reto",
last_name: "Meier",
display_name: "Reto Meier",
plusone_url: "https://plus.google.com/111169963967137030210/posts",
thumbnail_url: "http://storage.googleapis.com/io2012/headshots/retomeier.jpg",
user_id: "gooio2012/2177",
speaker_id: "gooio2012/101//gooio2012/2177"
}

Link: https://developers.google.com/events/io/session-details/gooio2012/210/

**Comment by helmuthb** [comment]
I will try to start with this.

**Comment by helmuthb** [comment]
Should be done now:
/json/event/<event-id>/speakers
