### ISSUE TITLE
Extend session model according to iosched3 model

### ISSUE THREAD

**Issue by printminion** [GoogleDeveloperGroups/devfest-site#2]
Please extend current session model according to iosched3 model (we need it for the app)
https://github.com/GoogleDeveloperGroups/devfest-site/blob/master/devfest-site/lib/model.py

{
room: "10",
start_date: "2012-06-27",
end_date: "2012-06-27",
start_time: "11:45",
end_time: "12:45",
level: "Intermediate",
track: [
"Android"
],
title: "What's New in Android?",
abstract: "This is a developer-centric tour of what’s gone into the system and application frameworks since the last time we got together. ",
attending: "N",
has_streaming: true,
livestream_url: "VuC0i4xTyrI",
youtube_url: [
"http://www.youtube.com/watch?v=Yc8YrVc47TI"
],
id: "gooio2012/105/",
tags: "Android",
speaker_id: [
"gooio2012/105//gooio2012/2179",
"gooio2012/105//gooio2012/2180",
"gooio2012/105//gooio2012/2157"
]
},

Link: https://developers.google.com/events/io/conference/session

**Comment by helmuthb** [comment]
Do you want to use globally unique tracks, or shall every event define its own tracks?

**Comment by printminion** [comment]
@helmuthb tracks are defined per event. Here are the tracks for/from the Google IO event.

{
 "track": [
   {
     "name": "Android",
     "color": "#A6BC40",
     "abstract": "Learn about developing mobile handset and tablet apps for Android."
   },
   {
     "name": "Chrome",
     "color": "#46B0E2",
     "abstract": "Build for the modern web with the Chrome platform."
   },
   {
     "name": "Cloud Platform",
     "color": "#2076BC",
     "abstract": "Learn about Google's cloud offerings for developers."
   },
   {
     "name": "Code Labs",
     "color": "#E4388F",
     "abstract": "Get your hands dirty in longer, classroom-style sessions. Bring your laptop. Write code."
   },
   {
     "name": "Commerce",
     "color": "#4CAA47",
     "abstract": "Learn how to use Google Commerce products to improve monetization on the web, in app, and in store."
   },
   {
     "name": "Entrepreneurship",
     "color": "#97B0DA",
     "abstract": "Talks on topics related to startups, venture capital, and entrepreneurship."
   },
   {
     "name": "Google APIs",
     "color": "#00773F",
     "abstract": "Learn about Google's various developer platforms."
   },
   {
     "name": "Google Drive",
     "color": "#F5851F",
     "abstract": "Learn to develop for Google Drive and Google Apps Script."
   },
   {
     "name": "Google Maps",
     "color": "#4CAA47",
     "abstract": "Leverage the power of Google's geospatial technology in your apps."
   },
   {
     "name": "Google TV",
     "color": "#37505C",
     "abstract": "Build apps for the big screen. Learn about developing for Google TV."
   },
   {
     "name": "Google+",
     "color": "#DC4E30",
     "abstract": "Learn about developing on the Google+ platform."
   },
   {
     "name": "Tech Talk",
     "color": "#A1609D",
     "abstract": "Tech talks on subjects such as computer science problems, programming languages, and more."
   },
   {
     "name": "YouTube",
     "color": "#E72C2E",
     "abstract": "Learn about developing for YouTube."
   }
 ]
}

**Comment by helmuthb** [comment]
should be done now:
/json/event/<eventid>/sessions and
/json/event/<eventid>/tracks
