### ISSUE TITLE
/event/create - "Timezone Offset of UTC" aka timezone field causes 500 

### ISSUE THREAD

**Issue by printminion** [GoogleDeveloperGroups/devfest-site#32]
New field "Timezone Offset of UTC"  breakes form submit

<input class="form_IntegerField" id="timezone" name="timezone" type="text" value="">

ERROR    2012-09-05 18:29:12,209 webapp2.py:1553] Property timezone must be an int or long, not a unicode

Tested with 73bccc090990dfecedbb9ea65b71a9527b65bd29

**Comment by helmuthb** [comment]
Did you specify a string? A numeric value like '2' would work.

Besides that an int value is not correct for e.g. Caracas or some areas in India.

**Comment by mthie** [comment]
India has UTC+5:30, so an int or long is not a good idea ;)
