### ISSUE TITLE
Create/Edit Event Pages Finalization

### ISSUE THREAD

**Issue by mthie** [GoogleDeveloperGroups/devfest-site#7]
We need to finalize the Create Event and Edit Event pages with the following features:
- add sponsors (with image upload?)
- add event days
- add schedule for each event day

**Comment by friedger** [comment]
I'll start with add sponors

**Comment by printminion** [comment]
@friedger could you do also the #8?

**Comment by helmuthb** [comment]
should be all done now.
We can open a new ticket "make it beautiful" :-)
