### ISSUE TITLE
Extend sponsor model according to iosched3 model

### ISSUE THREAD

**Issue by printminion** [GoogleDeveloperGroups/devfest-site#8]
Please extend current sponsor model according to iosched3 model (we need it for the app)
https://github.com/GoogleDeveloperGroups/devfest-site/blob/master/devfest-site/lib/model.py

iosched app feed: https://developers.google.com/events/io/sandbox-data

{
website: "www.testdroid.com",
product_pod: "Android",
company_description: "Testdroid is an automated testing solution for Android applications enabling use case based fully automated testing. Create tests once and run on any Android device.",
logo_vector: "Testdroid_Logo.pdf",
product_description: "Testdroid Cloud is an online service with over 100 real Android devices for fully automated device compatibility testing of Android applications. ",
exhibitors: [
"Jouko Kaasila",
"Sakari Rautiainen"
],
company_name: "Testdroid",
logo_img: "https://storage.googleapis.com/io2012/sandbox logos/Testdroid_Logo.png"
}

**Comment by mthie** [comment]
It's not only the model - we need some form fields to add and edit the contents ;)

**Comment by mthie** [comment]
Do you need it asap?

**Comment by mthie** [comment]
What content-type do you need in the logo_vector field?

**Comment by printminion** [comment]
@mthie it's just an idea how the google io people did it... ..I think logo_vector is not required

**Comment by mthie** [comment]
Okay, thank you :)

**Comment by printminion** [comment]
@mthie sorry the #8 (this) is about sponsor 
the #7 is about speakers and #6 - session

**Comment by mthie** [comment]
Already deleted my stupid comment :)

**Comment by friedger** [comment]
Added company description and name. Removed product_pod, product_description, exhibitors, logo_vectors

**Comment by helmuthb** [comment]
Should be done now: /json/event/<event-id>/sponsors
Except that currently only G+ pages are allowed (do we want to change this?)

**Comment by friedger** [comment]
No :-)
Am 30.08.2012 10:38 schrieb "Helmuth Breitenfellner" <
notifications@github.com>:
